# Generated by Django 4.2.6 on 2024-01-25 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("phone", models.IntegerField(max_length=255)),
                ("email", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("province", models.CharField(max_length=100)),
                ("created", models.DateField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to="app.user",
                    ),
                ),
            ],
        ),
    ]
